---
title: "Figuren ontwikkeling tijdsvarierende variabelen"
author: "Hanne Oberman"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

Load packages:
```{r env}
library(ggplot2)
library(dplyr)
```

Load the data:
```{r data}
load("imputaties.RData")
```

# Figures with linear trend acros time

Plot the outcome against the time:
```{r outcome}
ggplot(imp_post$data, aes(x = meting_mnd, y = q60_1)) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Vertrouwen") 
```

```{r onvrede}
ggplot(imp_post$data, aes(x = meting_mnd, y = round(onvr))) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Onvrede")
```

```{r mentaal}
ggplot(imp_post$data, aes(x = meting_mnd, y = round(ment))) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Mentale gevolgen")
```


```{r dreiging}
ggplot(imp_post$data, aes(x = meting_mnd, y = round(drei))) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Dreiging")
```

```{r contact}
ggplot(imp_post$data, aes(x = meting_mnd, y = round(cont))) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Sociaal contact")
```

```{r eenzaamheid}
ggplot(imp_post$data, aes(x = meting_mnd, y = round(eenz))) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Eenzaamheid")
```

```{r hulp}
ggplot(imp_post$data, aes(x = meting_mnd, y = round(hulp))) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  #scale_y_continuous(limits = c(1,5)) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Hulp ontvangen")
```

```{r mediagebruik}
ggplot(imp_post$data, aes(x = meting_mnd, y = round(medi))) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Mediagebruik")
```

```{r rondkomen}
ggplot(imp_post$data, aes(x = meting_mnd, y = round(rond))) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Rondkomen")
```

```{r gezo}
ggplot(imp_post$data, aes(x = meting_mnd, y = round(gezo))) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", na.rm = TRUE) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Gezondheid")
```

# Figure with average per timepoint

```{r groupmeans}
gd <- imp_post$data %>% 
        group_by(meting_mnd) %>% 
        summarise(q60_1 = mean(q60_1, na.rm = TRUE))
ggplot(imp_post$data, aes(x = meting_mnd, y = q60_1)) +
  geom_count(shape = 21, na.rm = TRUE, show.legend = FALSE) +
  geom_smooth(method = "lm", se = FALSE, color = "grey", linewidth = 2, na.rm = TRUE) +
  geom_line(data = gd, stat = "identity", linetype = "dotted", linewidth = 1) +
  scale_size_area(max_size = 10) +
  theme_classic() +
  labs(x = "Tijd (maanden)", y = "Vertrouwen") 


```

